#!/usr/bin/env bash

set -eo pipefail

IMAGE=${IMAGE:-CI_REGISTRY_IMAGE}

registry_credentials_available() {
    echo "Checking registry credentials"
    [[ -n "${CI_REGISTRY_USER}" ]] && [[ -n "${CI_REGISTRY_PASSWORD}" ]] && return 0
    return 1
}

login() {
    echo "Logging into registry"
    registry_credentials_available || return 0
    docker login --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
}

logout() {
    echo "Logging out from registry"
    registry_credentials_available || return 0
    docker logout ${CI_REGISTRY}
}

pull () {
    echo "Pulling base image"
    registry_credentials_available || return 0
    docker pull ${IMAGE} || echo "${IMAGE} image is not available. Will not use cache."
}

push () {
    echo "Pushing image"
    registry_credentials_available || return 0
    docker push ${IMAGE}
}
